language: python
python: '3.5'
branches:
  only:
  - master
  - develop
install:
- pip install coverage codacy-coverage
script:
- coverage run -m py.test tests
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: lexycore
  password:
    secure: YJQzD7ubdcX9ShJIx3KJTMMgURhQfFbELHS7cJjx1TRqNoMBSbGc4PXLBPo0OsE7+C3DC4wLMEQdXVSkSdhttjZvuhoBtGtTATcmpAqQDKo+RNftirjVdGczAMkaR0Fdjk2LZKxcnWOgmgif/SbcKi+PbxJqvfPmOiw2J+hccy1f+xa2kr3RlW+oyWxUzuOcHfPmZZuPwX211/Eu92Y/c0Ygxv5r1JWA9f6i1U5BeetjresWXBWTBhybT90DD+Q+ez8/eURcA6/fAqkGgrvyH38ok1yqGIV3FZFTNObk/Aue8iDMrcWjQZPWCugwBM/3+DJQmH3AXgx1vpHtUV91FTAxt3aQmyHEGzK8a3mPdZnkeXbbN04xOCHfqB/XNhqJkMTVI48D9B/aLhMJR/eqXubWKtnjnbaok4lnFBZMGIhKTijnwpywQYP3utR/+t5GrGAaWvaa6rDnMIR3NJ1qp/A9RV5GNCjhspvJlzMdOo0IKMIaWEEWYp78gR504d8fQ+e6c+hVbFFBPGaIPKX87RzCAFMkF3HZmpqJ+8eYW9XQ+LDi7I+hh0JP5d/PItt90M+FlzS78BRhIOkSJsbrYGaEBjo5cLihga9TBTfs17YcXFlozJYPMhm44evziC0ocjcid8riI18zgEIoOlhh0LVs9gEEV1TDkUX4LULTKWs=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
    secure: eyfHa8cF4+qEb3jIfghf87ysCHyphHhItEkRoJ9aY+rklgRTvpRrudmRwk/o7yYP7Lg1rZqnpL4Xan5ae3MMg5pyIGo05aDkMJRIaqbVNbz+GFV6EkFP0Q1SkDlSaE5wMopTzLYoeeXlh7eYCisamaIaMyePknaJ8YouA7Ag8KqdBRRUR1sHMJtzrfXWqPGTa4blaAtsTUmbEq6bB60fN0CC92T+7YxiYXDuDblfdUtcu4GFnYAqgY/8gv+Y+jQ9Y7ldJQqKVtkvRIiQwGMOQwOGN02U7zDvvNLk5HkXP7+tvmEtAYCAraCg+f+6VzslptxT0F7qbCfPABuUnewcLPatHRooW08KsvTXDBvrpZuHI4Jxo/1ZBEh3qK7ruUAT202J60XhqMU3i5VCOYYL8NtcyrSzcW/Xyt8gTCFXlgaNG7jTnjz6cnC0okbxtKwPUdOCbK+pGci8Nk57TyQj5iL0oboXqjVfuvd6mTcF6OULjSvqJ5A8UKsKeFyBlMjgU4HJxczUt7h+gqwJofbJr9D9g1H1iEhA2JP2hbK3BNOnGYs7K2AqlmpcZi5F8q0V+4UjQ+kt0uIBICm/G4KRuF/KEcuTxa0q30TSOTLwrpdsGdZkfezR+2YdBEUM5RkIZ6ths4Rp5CMxjGTFca4DEg2nGcBezJumx1+ItJttRhY=
