language: python
python: '3.5'
addons:
  apt_packages:
  - pandoc
branches:
  only:
  - master
  - develop
services:
- redis-server
install:
- pip install redis pypandoc coverage codacy-coverage
script:
- coverage run -m py.test tests
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: lexycore
  password:
    secure: VIqS0I3T1DbmGFDFEgJbESf8nH/llOrgQF3IaZLm3ZFV61cSfIJx7T/2eniuxFzMsxGQA0lT/88MwD6awe5KXnIDuDBEBmFPXG8JUH5ZBkBgYwpnIYPuORPsoMFhmXn0DdHr//hk1rAVWlt+KrdkA8w6pO1fEaevhGgzPA8ua0S/pcbGDj20mHVIGylg7khe0XzOoBJQpcYMO8F/figLWyNeo0lyg9gxwF2vcJOlhi6cvd7NGTHvTDX7ftKzqqO5RqmlpjKdCAZ14+4rfaTTKXfFmErKT2cuEQu5ln7qz/QuUbYko/PKmpqUn0gGol3iFRSBZEYC7mHzLf4rBwNO13X+VpMr+yjcltvhVCa8wTrFBl/c0FiWfayFTs83okQ0EPdFWc+g+EjVtB7H/37PLRtpw6sg12D12AcM7bbutjKNDBlvE+dFUnGfbHuURC4+6km/Ol46yk1H36jLg2aG7cNCLdITag8XJIL0N1UbY6rGTYZOMdzzlwxRAlUmlPjnnRFZRK1guXB02G6pJYPbwgpwwPhonI/gwAa62c+3xTocKTz0eoe+ArO8g8+98kpCLGdp4Vld9uI0GL6n93AnHVPWfOg2MSqvgxepxEw+ISJJMfzusS/bsROyVn/89jRH2OaO3lEZTLNRsMlU8P0O6D5uvw9uJOBeYxlWCnu55lc=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
    secure: eyfHa8cF4+qEb3jIfghf87ysCHyphHhItEkRoJ9aY+rklgRTvpRrudmRwk/o7yYP7Lg1rZqnpL4Xan5ae3MMg5pyIGo05aDkMJRIaqbVNbz+GFV6EkFP0Q1SkDlSaE5wMopTzLYoeeXlh7eYCisamaIaMyePknaJ8YouA7Ag8KqdBRRUR1sHMJtzrfXWqPGTa4blaAtsTUmbEq6bB60fN0CC92T+7YxiYXDuDblfdUtcu4GFnYAqgY/8gv+Y+jQ9Y7ldJQqKVtkvRIiQwGMOQwOGN02U7zDvvNLk5HkXP7+tvmEtAYCAraCg+f+6VzslptxT0F7qbCfPABuUnewcLPatHRooW08KsvTXDBvrpZuHI4Jxo/1ZBEh3qK7ruUAT202J60XhqMU3i5VCOYYL8NtcyrSzcW/Xyt8gTCFXlgaNG7jTnjz6cnC0okbxtKwPUdOCbK+pGci8Nk57TyQj5iL0oboXqjVfuvd6mTcF6OULjSvqJ5A8UKsKeFyBlMjgU4HJxczUt7h+gqwJofbJr9D9g1H1iEhA2JP2hbK3BNOnGYs7K2AqlmpcZi5F8q0V+4UjQ+kt0uIBICm/G4KRuF/KEcuTxa0q30TSOTLwrpdsGdZkfezR+2YdBEUM5RkIZ6ths4Rp5CMxjGTFca4DEg2nGcBezJumx1+ItJttRhY=
